### ISSUE TITLE
Performance of the provider for firewall with thousands of policies

### ISSUE THREAD

**Issue by eoprede** [fortinetdev/terraform-provider-fortios#327] opened 2024-05-28 13:26 UTC
Hello,
I have just started using this provider to manage firewall policies and it works great. As I have moved from from managing 10 rules to 200 rules, I am observing an increase of tf plan/apply run from 5 seconds to roughly 20 seconds, I am also observing CPU load spiking during the plan/apply process (though it appears that the spike is only on one core).
I am hoping to scale this up to thousands of rules (current estimate is about 15000 per FW) and I am wondering - are any performance limitations when managing so many rules? And if yes, any suggestions on how to mitigate them?
Thanks!

**Comment by MaxxLiu22** [comment] 2024-05-30 22:39
Hi @eoprede ,

Thank you for raising this issue. May I ask if you have considered using a token as an authentication method? This approach is a more efficient way to deploy the configuration to the FGT. To do so, you would need to create an API user with the appropriate access profile, generate a token, and then save this token into your FOS provider. This method allows around 1 second for each policy creation for a total 200 policies test.
``` 
FGT-VM-103 # config system api-user 

FGT-VM-103 (api-user) # edit api 

FGT-VM-103 (api) # show
config system api-user
    edit "api"
        set api-key ENC SH2H8D+CERHglbDgDEw1BvAn0t2OFfYmrY4uhf6oKBF79JkDQYU3jIOXh/BLag=
        set accprofile "super_admin"
        set vdom "root"
    next
end

FGT-VM-103 (api) # end

FGT-VM-103 # execute api-user generate-key api 

New API key: HGphmrNn30qbmnb1hm4cnGpjs53zzN

NOTE: The bearer of this API key will be granted all access privileges assigned to the api-user api.
```
```
terraform {
  required_providers {
    fortios = {
      source  = "fortinetdev/fortios"
      version = "1.19.1"
    }
  }
}
provider "fortios" {
  hostname = "10.160.x.x"
  # username = "user"
  # password = "psw"
  token    = "HGphmrNn30qbmnb1hm4cnGpjs53zzN"
  insecure      = true
}
```
```
fortios_firewall_policy.sample_policy_29: Creation complete after 1s [id=193]
fortios_firewall_policy.sample_policy_136: Creation complete after 1s [id=194]
fortios_firewall_policy.sample_policy_165: Creating...
fortios_firewall_policy.sample_policy_90: Creation complete after 0s [id=195]
fortios_firewall_policy.sample_policy_91: Creation complete after 1s [id=197]
fortios_firewall_policy.sample_policy_135: Creation complete after 1s [id=196]
fortios_firewall_policy.sample_policy_166: Creation complete after 1s [id=198]
fortios_firewall_policy.sample_policy_165: Creation complete after 1s [id=199]
```
Thanks,
Maxx

**Comment by eoprede** [comment] 2024-05-30 23:10
@MaxxLiu22 
Yes, I am using token authentication already. The issue is not with the creation part. The issue is with the terraform plan part - from what I understand, the module does a separate API query for each single resource, which means if I have 20000 policies and address objects - the module will do 20K api calls. Even with a few hundred objects I am noticing one of the CPU cores hitting 100% utilization. Right not it only lasts about 10 seconds, but it could be well over a minute if the scaling is linear. I am concerned with a) overall module performance and b) performance of the firewall once I start managing 20000 objects.

**Comment by MaxxLiu22** [comment] 2024-06-03 23:44
Hi @eoprede ,

I understand your concern, and I believe it is caused by the Terraform mechanism. I found this Terraform GitHub [case](https://github.com/hashicorp/terraform/issues/18981) discussing the issue. If you would like to skip the state refreshing process, you can run ``terraform apply -refresh=false``, which will only compare the differences between the local state file and the configuration file.

Alternatively, we can divide these 20,000 policies into various clusters to manage them separately, which will also shorten the apply time. I have also found some other workaround methods [here](https://github.com/hashicorp/terraform/issues/18981), such as setting [lifecycle](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) to define which resources need to be refreshed during apply, or using the [workspace](https://developer.hashicorp.com/terraform/language/state/workspaces) method to break a large project into clusters.

I hope one of these methods meets your needs. Please let me know if you need any further assistance.

Thanks,
Maxx

**Comment by eoprede** [comment] 2024-06-04 18:24
Thank you @MaxxLiu22 
I can use different methods in terraform to improve run times, but what about the Firewalls? Will I experience any performance degradation if one CPU core stays at 100% load for a prolonged time (let's say a minute)?

**Comment by MaxxLiu22** [comment] 2024-09-05 23:05
Hi @eoprede,

Apologies for the delayed response. After conducting several tests, we found that managing 2,000 policies and adding 5 more policies within the same workspace results in a longer creation time (impacted by terraform mechanism). However, if 5 additional policies are added to an FGT with 2,000 existing policies using a separate workspace, the results are comparable to adding 5 policies to a clean FGT. If there are concerns about one CPU running at 100% and potentially affecting the FGT’s overall traffic performance, I would recommend enabling the npu [dedicated-management-cpu](https://docs.fortinet.com/document/fortigate/7.6.0/hardware-acceleration/868858/improving-gui-and-cli-responsiveness-dedicated-management-cpu) feature. This isolates one CPU for management tasks, preventing any impact on other functionalities. I attach the information I find here and let me know if that doesn't solve your questions.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/liangl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/liangl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Action | Creation Time
-- | --
create 2000 firewall policies | 24m32.661s
create 5 firewall policies | 0m2.851s
add 5 policies to existing 2000 policies   in one workspace -refresh=false | 1m2.455s
add 5 policies to existing 2000 policies   in one workspace -refresh=true | 4m10.434s
add 5 policies to existing 2000 policies   in a seperate workspace | 0m2.938s
![disable_dmc](https://github.com/user-attachments/assets/6f5a0648-75ad-4133-bb2e-d2a03f8a8c33)


![enable_dmc](https://github.com/user-attachments/assets/68423798-e5d5-48eb-b3fc-99ccaa9f63b7)


</body>

</html>

Thanks,
Maxx

**Comment by MaxxLiu22** [comment] 2024-10-24 01:42
I will proceed with closing this case. However, feel free to reopen it if you continue to experience this issue.

**Closed by MaxxLiu22** 2024-10-24 01:42 UTC
