### ISSUE TITLE
Creating resource fortios_webfilter_profile fails with 500 error

### ISSUE THREAD

**Issue by TathanT** [fortinetdev/terraform-provider-fortios#273] opened 2023-04-26 20:06 UTC
Best I can tell, I am passing all the required arguments AND the two resources in question get created. The urlfilter resource is created without issue, then when attempting to create the webfilter_profile resource, I get the following error:
```
Error: Error creating WebfilterProfile resource: Internal Server Error - Internal error when processing the request (500)
│
│   with fortios_webfilter_profile.RULENAMEProfile,
│   on FIREWALL.tf line 99, in resource "fortios_webfilter_profile" "RULENAMEProfile":
│   99: resource "fortios_webfilter_profile" "RULENAMEProfile" {
│
```

The Terraform Config is:
```resource "fortios_webfilter_urlfilter" "RULENAME" {
  fosid                 = 6
  name                  = "RULENAME"
  entries {
    type = "wildcard"
    url = "testurl.com/abc*"
    action = "allow"
  }
}

resource "fortios_webfilter_profile" "RULENAMEProfile" {
  name                  = "RULENAME"
  comment = "Web Filter to allow hosts to URL"
  web {
    urlfilter_table     = 6
  }
}
```

And finally, the firewall output is:
```
FIREWALL # config webfilter profile 

 

FIREWALL (profile) # show

config webfilter profile
    edit "RULENAME"

        set comment "Web Filter to allow hosts to URL"

        config file-filter

            set status disable

            set log disable

            set scan-archive-contents disable

        end

        config override

            set ovrd-cookie allow

        end

        config web

            set bword-threshold 0

            set urlfilter-table 6

        end

    next

end

FIREWALL (urlfilter) # show
config webfilter urlfilter
    edit 6

        set name "RULENAME"

        config entries

            edit 1

                set url "testurl.com/abc*"

                set type wildcard

                set action allow

            next

        end

    next

end
```

I'm not sure if this is a bug, or if I'm missing something (obvious or not)? Thanks in advance for looking at this

**Comment by MaxxLiu22** [comment] 2023-04-26 20:37
Hi @TathanT ,

Thank you for your question, this issue may caused by this object has already been created at the first time but not be recorded in terraform state file, since this fortios_webfilter_profile resource uses urlfilter resource you created before, we need to use depend_on function to define the create order like following code, otherwise fortios_webfilter_profile may be created partially on fgt first, and not be record in state file.
```
resource "fortios_webfilter_urlfilter" "trname" {
  fosid                 = 6
  name                  = "RULENAME"
  entries {
    type = "wildcard"
    url = "testurl.com/abc*"
    action = "allow"
  }
}

resource "fortios_webfilter_profile" "RULENAMEProfile" {
  name                  = "RULENAME"
  comment = "Web Filter to allow hosts to URL"
  web {
    urlfilter_table     = 6
  }
depend_on = ['fortios_webfilter_urlfilter.trname']
}
```
now you can manually import the fortios webfilter profile by running ``terraform import fortios_webfilter_profile.RULENAMEProfile RULENAME``, or you can delete the existing fortios webfilter profile through cli, and let terraform to create it again, let me know if that doesn't fix your problem.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment] 2023-07-07 17:12
glad to hear that, I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.

**Closed by MaxxLiu22** 2023-07-07 17:12 UTC
