### ISSUE TITLE
user_ldap name seems to be required not optional

### ISSUE THREAD

**Issue by jzamanski-pm** [fortinetdev/terraform-provider-fortios#298] opened 2023-10-13 21:40 UTC
https://github.com/fortinetdev/terraform-provider-fortios/blob/cd5ed5417300f3bb658b89886ca7dde3f60685c7/fortios/resource_user_ldap.go#L42C4-L42C24

when creating a new user_ldap resource without providing an optional name i'm getting a 500 error
providing the name field fixed it

name is not being sent in the HTTP POST when omitted so if it's supposed to be inferred from the terraform resource name or something that doesn't seem to be working right

**Comment by MaxxLiu22** [comment] 2023-10-16 17:54
Hi @jzamanski-pm ,

Thank you for raising this issue, reproduced on fortios 7.2.5, name should be a required argument, I have reported it the development team for advice.

Thanks,
Maxx

**Comment by jzamanski-pm** [comment] 2023-10-18 20:06
Hi Maxx,
The same appears to be true for fortios_system_linkmonitor.
Thanks,
Jeff

**Comment by lix-fortinet** [comment] 2024-06-05 23:20
Hi @jzamanski-pm,

This issue has been fixed since FortiOS Terraform provider v1.18.1. I will close this issue and feel free to open a new issue if you have any questions.

Thanks,
Xing

**Closed by lix-fortinet** 2024-06-05 23:20 UTC
