### ISSUE TITLE
Import of BGP configurations is not full

### ISSUE THREAD

**Issue by trrogi** [fortinetdev/terraform-provider-fortios#267] opened 2023-04-10 10:31 UTC
I trying to import BGP configuration with "terraform import fortios_router_bgp.testbgp RouterBgp", but resulting state is lacking AS number which is mandatory and neighbors block. Using FTG v7.2.4, terraform v1.4.2 and frotios provider v1.16.0.
Similar import problems i have with prefixlists and route-maps, they lack rule blocks.(https://github.com/fortinetdev/terraform-provider-fortios/issues/261)

**Comment by MaxxLiu22** [comment] 2023-04-10 20:49
Hi @trrogi ,

Thank you for raising this issue, I can reproduce this problem, that may caused by data type change during FOS evolving. I have reported it to the development team.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment] 2024-09-16 18:51
Hi @trrogi 

I try to reproduce this issue with Terraform FOS 1.21.0 again, it did not recur after running export ``FORTIOS_IMPORT_TABLE=true`` and importing the fortios_router_bgp, ``as`` and ``neighbors block`` are successfully imported into state file. Therefore, I will proceed to close this case. If you have any further questions or need additional assistance, please feel free to reopen this case or open a new one, and we will be happy to help.

Thank you,
Maxx

**Closed by MaxxLiu22** 2024-09-16 18:51 UTC
