### ISSUE TITLE
fortios_router_accesslist does not put exact_match properly

### ISSUE THREAD

**Issue by blkistsg** [fortinetdev/terraform-provider-fortios#107] opened 2020-10-23 17:31 UTC
It creates, but exact_match is set to disable whether you set enable or not.

Tested on FortiOS 6.4

```
resource "fortios_router_accesslist" "static_ospf_redistribution_networks" {
name = "static-redistribution"
comments = "Used to specify networks which get redistributed into OSPF"

rule
{ id = 10 action = "permit" prefix = "10.0.0.0 255.0.0.0" exact_match = "enable" }

}
```

![image-2020-09-01-13-25-51-307](https://user-images.githubusercontent.com/71094995/97035263-159c9c80-1534-11eb-950e-5d37cb48bf65.png)

**Comment by frankshen01** [comment] 2020-10-28 14:38
@blkistsg   The issue is a duplicate of #99. Will close it. Thank you!

**Closed by frankshen01** 2020-10-28 14:38 UTC
