### ISSUE TITLE
fortios_certificate_remote is not working

### ISSUE THREAD

**Issue by rpuserh** [fortinetdev/terraform-provider-fortios#216] opened 2022-03-04 22:29 UTC
Hi,

This method is not working.

```
resource "fortios_certificate_remote" "azure_sso_cert" {
  name = "REMOTE_Cert_1"
  remote = base64decode("bae64Encodedkey")
  range = "global"
  source = "user"
}
```
 After apply I cannot see it in fortigate.
When trying to apply multiple time it always has changes 

Please advice.

**Comment by lix-fortinet** [comment] 2022-03-10 01:08
Hi @rpuserh,

Thank you for raising this issue. Some resource may not show on GUI. But you could find it by CLI.
For instance:
```
config global
  config certificate remote
      edit "REMOTE_Cert_1"
      next
  end
end
```

We asked GUI team about this issue, and we will get back to you once they replied.

Thanks,
Xing

**Comment by lix-fortinet** [comment] 2022-03-18 00:56
Hi @rpuserh,

GUI team said that the certificate will not be shown on GUI if the content of the argument `remote` is not valid, even you could find it in CLI. The issue is REST API should not return 200OK if the certificate content is invalid and has CLI error. An internal ticket has been created for this issue, and we will get back to you when API team has a solution for it. By the way, by the requirement of API format, the content of argument `remote` needs to add additional `\"` at the start and end of it. Like `"\"-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\""`. 

For your configuration:
```
resource "fortios_certificate_remote" "azure_sso_cert" {
  name = "REMOTE_Cert_1"
  remote = "\"${base64decode("bae64Encodedkey")}\""
  range = "global"
  source = "user"
}
```

Thanks,
Xing

**Comment by lix-fortinet** [comment] 2022-04-28 22:26
Hi @rpuserh,

The latest release of FortiOS Terraform provider v1.14.1 handled the format issue of certificate content. You do not need to add additional `\"` for the certificate content. For your case, it will be:
```
resource "fortios_certificate_remote" "azure_sso_cert" {
  name = "REMOTE_Cert_1"
  remote = base64decode("bae64Encodedkey")
  range = "global"
  source = "user"
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by Woitekku** [comment] 2022-09-29 11:47
The issue is not resolved. 

Neither:
```
resource "fortios_certificate_remote" "this" {
  name = "REMOTE_Cert_1"
  range = "global"
  remote = base64decode(<basse64 encoded cert")
  source = "user"
}
```
nor:
```
resource "fortios_certificate_remote" "this" {
  name = "REMOTE_Cert_1"
  range = "global"
  remote = file("Cert.pem")
  source = "user"
}
```

works...

TF plan/apply shows it correctly, but the the cert is not visible, in gui and in cli... simply it's not there... 


Can we have another look on this?

**Comment by lix-fortinet** [comment] 2022-09-29 23:44
Hi @Woitekku,

Could I know the FortiOS version and FortiOS Terraform provider version in your environment? I tested in my end and it works.
![image](https://user-images.githubusercontent.com/71158051/193160791-9e548a62-77f7-47b9-a3a6-4b98427aa9e5.png)


Thanks,
Xing

**Comment by MaxxLiu22** [comment] 2023-07-07 19:21
Hi @Woitekku ,

I will go ahead to close this case, if your question is still not solved, feel free to reopen it or another case.

Thanks,
Maxx

**Closed by MaxxLiu22** 2023-07-07 19:21 UTC
