### ISSUE TITLE
Receiving error reading FirewallProfileProtocolOptions

### ISSUE THREAD

**Issue by leonardoauribe** [fortinetdev/terraform-provider-fortios#222] opened 2022-03-25 19:22 UTC
After importing our existing protocol options resources receiving the following error when attempting to run a terraform apply;

"Error reading FirewallProfileProtocolOptions resource from API: Error reading http: http.0.ports: '' expected type 'int', got unconvertible type 'string'"

It appears that terraform doesn't like the fact that the "http" block doesn't have a port defined. We don't require a port to be defined as this configuration is meant to inspect all ports. I ran a debug that provided a more detailed output (below). 

```
module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options[0]: Refreshing state... [id=test-proxy]
2022-03-15T21:01:27.228Z [TRACE] GRPCProvider: ReadResource
2022-03-15T21:01:27.232Z [DEBUG] provider.terraform-provider-fortios_v1.13.1: 2022/03/15 21:01:27 FOS-fortios reading response: {
2022-03-15T21:01:27.232Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "http_method":"GET",
2022-03-15T21:01:27.232Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "revision":"a1f2a481966a2660b9939b8090e12124",
2022-03-15T21:01:27.232Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "results":[
2022-03-15T21:01:27.232Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:     {
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "name":"test-proxy",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "q_origin_key":"test-proxy",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "comment":"[TF]",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "replacemsg-group":"",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "oversize-log":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "switching-protocols-log":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "http":{
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":"",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"enable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "proxy-after-tcp-handshake":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-interval":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-amount":1,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "range-block":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "strip-x-forwarded-for":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "post-lang":"",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "streaming-content-bypass":"enable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "switching-protocols":"bypass",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "unknown-http-version":"reject",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tunnel-non-http":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "stream-based-uncompressed-limit":0,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "block-page-status-code":403,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "retry-count":0,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-type":"system",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-minimum":131072,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-maximum":8388608,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-size":262144,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ssl-offloaded":"no"
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "ftp":{
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           21
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"disable",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"splice",
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-interval":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-amount":1,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.233Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ssl-offloaded":"no"
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "imap":{
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           143
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"disable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "proxy-after-tcp-handshake":"disable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"fragmail",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ssl-offloaded":"no"
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "mapi":{
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           135
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"fragmail",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable"
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "pop3":{
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           110
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"disable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "proxy-after-tcp-handshake":"disable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"fragmail",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ssl-offloaded":"no"
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "smtp":{
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           25
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.234Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"disable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "proxy-after-tcp-handshake":"disable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"splice",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "server-busy":"disable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ssl-offloaded":"no"
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "nntp":{
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           119
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "inspect-all":"disable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "proxy-after-tcp-handshake":"disable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"splice",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable"
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "ssh":{
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-interval":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "comfort-amount":1,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable"
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "dns":{
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           53
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable"
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "cifs":{
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "ports":[
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:           445
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ],
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"enable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "options":"",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-oversize-limit":10,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "uncompressed-nest-limit":12,
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "scan-bzip2":"enable",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-type":"system",
2022-03-15T21:01:27.235Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-minimum":131072,
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-maximum":8388608,
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "tcp-window-size":262144,
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "server-credential-type":"none",
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "domain-controller":"",
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "server-keytab":[
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         ]
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "mail-signature":{
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "status":"disable",
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:         "signature":""
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       },
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:       "rpc-over-http":"enable"
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:     }
2022-03-15T21:01:27.236Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   ],
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "vdom":"root",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "path":"firewall",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "name":"profile-protocol-options",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "mkey":"test-proxy",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "status":"success",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "http_status":200,
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "serial":"FGTAWS123456789",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "version":"v6.4.7",
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1:   "build":1911
2022-03-15T21:01:27.237Z [DEBUG] provider.terraform-provider-fortios_v1.13.1: }
2022-03-15T21:01:27.238Z [TRACE] vertex "module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options[0]": visit complete
2022-03-15T21:01:27.238Z [TRACE] vertex "module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options": dynamic subgraph encountered errors: Error reading FirewallProfileProtocolOptions resource from API: Error reading http: http.0.ports: '' expected type 'int', got unconvertible type 'string'
2022-03-15T21:01:27.238Z [TRACE] vertex "module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options": visit complete
2022-03-15T21:01:27.238Z [TRACE] vertex "module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options (expand)": dynamic subgraph encountered errors: Error reading FirewallProfileProtocolOptions resource from API: Error reading http: http.0.ports: '' expected type 'int', got unconvertible type 'string'
2022-03-15T21:01:27.238Z [TRACE] vertex "module.policy_objects.fortios_firewall_profileprotocoloptions.proxy_protocol_options (expand)": visit complete
2022-03-15T21:01:27.238Z [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/fortinetdev/fortios\"] (close)" errored, so skipping
2022-03-15T21:01:27.238Z [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2022-03-15T21:01:27.238Z [TRACE] dag/walk: upstream of "root" errored, so skipping
```

Expecting resource to be applied with no issues.

**Comment by lix-fortinet** [comment] 2022-03-30 19:01
Hi @leonardoauribe,

Thank you for raising this issue. This issue is caused by the inconsistency of the type of argument `ports` from HTTP response. It will be a list if have content, but a string if it is empty. Team is working on this issue to handle it on Terraform provider side, and we will get back to you once it's resolved. 

Thanks,
Xing

**Comment by lix-fortinet** [comment] 2022-04-28 22:37
Hi @leonardoauribe,

The latest version of FortiOS Terraform provider v1.14.1 fixed this issue. Please switch to v1.14.1 and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by leonardoauribe** [comment] 2022-05-09 20:39
Will give that a try. thanks!

**Comment by lix-fortinet** [comment] 2022-10-10 20:53
Hi @leonardoauribe,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing

**Closed by lix-fortinet** 2022-10-10 20:53 UTC
